DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  relationship_status VARCHAR(255) NOT NULL,
  image_url VARCHAR(255) NOT NULL,
  birthday DATE,
  location VARCHAR(255) NOT NULL
);